# 프로젝트 이름
name = "2024-02-bdad-study"

# SvelteKit의 빌드 출력 위치 지정
main = "build"

[site]
# Cloudflare Pages를 위한 빌드 출력 디렉토리
bucket = "./build"

# 배포할 디렉토리 지정
entry-point = "./build"

[env.production]
# 개발 모드 비활성화
workers_dev = false
