name: Deploy to Cloudflare Pages
on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build with pnpm
        run: pnpm run build

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'build'
          path: 'build/'

  deploy:
    runs-on: ubuntu-latest
    needs: build_site
    environment: 2024-02-bdad-study-cloudflare-pages
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: 'build/'
      
      - name: List build directory contents
        run: |
          pwd
          ls -l .
          du -h --max-depth 1
          ls -l ./build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: .
          command: pages deploy --project-name 2024-02-bdad-study ./build
